### ISSUE TITLE
Implement mood protocol from app 

### ISSUE THREAD

**Issue by ibevers** [sensein/b2aiprotocol#2]
#### Forms
- [x] Demographics
- [x] Confounders
- [x] Voice Perception
- [x] VHI-10
- [x] PHQ-9
- [x] GAD-7 Anxiety
#### Audio
 - [x] Audio check (same as mood)
- [x] Prolonged vowel
- [x] Maximum phonation time
- [x] Rainbow Passage
- [x] Glides
- [x] Loudness
- [x] Diadochokinesis
- [x] Free speech
- [x] Respiration and cough
- [x] Picture description
- [x] Story recall

#### Forms
 - [x] PANAS
 - [x] Custom Affect Scale
 - [x] DSM-5 Adult
 - [x] PTSD Adult
 - [x] ADHD Adult
 #### Audio
 - [x] Audio check (same as mood)
 - [x] Animal fluency
 - [x] Open response questions

**Comment by ibevers** [comment]
demographics not runnable because of UI bug (I think)--isVis conditions

**Comment by satra** [comment]
did you run validator? and verify bug? can you describe what non-runnable looks like?

**Comment by ibevers** [comment]
The `demographics` activity passes validation, and it is runnable on its own:
https://www.repronim.org/reproschema-ui/#/?url=
https://raw.githubusercontent.com/sensein/b2ai-redcap2rs/main/activities/q_generic_demographics/q_generic_demographics_schema

Pretty sure there is an issue with the order of the state initialization in the UI. `gender_identity` is used in many `isVis` conditions in demographics. I think it is trying to resolve the `isVis` conditions before the user responds to the `gender_identity` item. I don't know if this actually matters.
<img width="562" alt="Screenshot 2024-07-17 at 10 00 14 AM" src="https://github.com/user-attachments/assets/ae747cb4-4807-459a-a976-8c8597afd4e4">

The not runnable part may be due to another issue in `b2aiprotocol`.

**Comment by satra** [comment]
@ibevers - that protocol converted from redcap is separating out data elements that need to be combined. so a direct conversion from the tool is incorrect. this will have to be manually edited to turn the different categories into responsechoices
